name: Run Short PUT Script

on:
  schedule:
    - cron: '30 1 * * *'  # 03:30 CEST (01:30 UTC)
    - cron: '0 15 * * *'  # 17:00 CEST (15:00 UTC)
    - cron: '0 19 * * *'  # 21:00 CEST (19:00 UTC)
  workflow_dispatch:  # Permite ejecución manual

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy requests

      - name: Run script
        env:
          DISCORD_WEBHOOK_URL_NASDAQ: ${{ secrets.DISCORD_WEBHOOK_URL_NASDAQ }}
        run: |
          python main.py || { echo "Script failed with exit code $?"; exit 1; }
